# Generated by Django 2.2.9 on 2022-12-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221217_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': ('Группа',)},
        ),
    ]
