# Generated by Django 2.2.16 on 2023-01-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20230111_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Вы можете добавить изображение к вашему посту', upload_to='', verbose_name='Картинка'),
        ),
    ]
