# Generated by Django 2.2.16 on 2023-01-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20230113_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Вы можете добавить изображение к вашему посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
